---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - name: i want to execute linux commands 
    command: hostname -f
    register: myresult

  - name: i want to display first result 
    debug:
       msg: "{{myresult}}"

  - name: install git 
    apt:
      name: git
      state: present 
    when: myresult.stderr!=""

  - name: install tree
    apt: 
      name: tree
      state: present 
    when: myresult.stderr==""

  