---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - name: i want to execute linux commands 
    command: hostname -f
    register: myresult

  - name: i want to display first result 
    debug:
       msg: "{{myresult}}"


  