---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: create a directory
    file: 
      path: /home/maha/myfodler
      state: directory

  - name: copy static file
    copy:
      src: mystaticfile
      dest: /home/maha/myfodler/mystaticfile

  - name:  download internet files
    get_url:
        url: https://github.com/maha4dsvc/myAnsible-DS-9am-30dec24/blob/main/myStudents.yml
        dest: /home/maha/myfodler/myStudents.yml
        force_basic_auth: yes

  - name: i want to install webserver
    apt:
      name: apache2 
      state: present 

  - name: i want copy index file into node side
    template:
         src: myindex.j2
         dest: /var/www/html/index.html

    
