---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install apache2 webservr on ubuntu node side
    apt:
      name: "{{mywebpackoubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
      
  - name: i want to start webserver (service apache2 start) on ubuntu node
    service: 
        name: "{{mywebpackoubuntu}}" 
        state: started
    when: ansible_os_family=="Debian"


  - name: install httpd webserver on RedHat nodes
    dnf:
       name: "{{mywebpackonRedhat}}"
       state: present
    when: ansible_os_family=="RedHat"

  - name: start httpd webserver  on RedHat node
    service:
       name: "{{mywebpackonRedhat}}"
       state: started
    when: ansible_os_family =="RedHat"
      

