---
- name: download tomcat tar file
  get_url:
    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.34/bin/apache-tomcat-10.1.34.tar.gz
    dest: /home/ubuntu/apache-tomcat-10.1.34.tar.gz
    force_basic_auth: yes
  
- name: create tomcat folder
  file:
    path: /opt/tomcat
    state: directory

- name: extract tar file into tomcat folder 
  unarchive:
    src: /home/ubuntu/apache-tomcat-10.1.34.tar.gz
    dest: /opt/tomcat/
    remote_src: yes

