---
- name: create a group
  group: 
     name: tomcat
     state: present 

- name: create a user
  user: 
     name: tomcat
     shell: /bin/false
     home: /opt/tomcat 
     group: tomcat
     state: present 
    
- name: grant change owner on tomcat  folder
  command: sudo chown -R tomcat /opt/tomcat/apache-tomcat-10.1.34

- name: grant change execute  on bin  folder
  command: sudo sh -c 'chmod +x /opt/tomcat/apache-tomcat-10.1.34/bin/*.sh'

